backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "portfolio_items" # Used in routes, e.g., /admin/collections/sections
    label: "Sessão de portfólio" # Used in the UI
    format: json
    public_folder: 'https://construtoraconfidence.com/uploads'
    folder: "public/portfolio_items/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fields.titulo}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      #- {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Título", name: "titulo", widget: "string"}
        name: "sessions"
        widget: "list"
        allow_add: true
        fields: 
          - {label: "Foto", name: "foto", widget: "file"}
          - {label: "Título", name: "titulo", widget: "string"}
          - {label: "Descrição curta", name: "shortstory", widget: "text"}
          - {label: "Descrição longa", name: "tailstory", widget: "text"}
          - {label: "MD Session", name: "mdsession", widget: "markdown"}
              
      - label: "Story"
        name: story
        widget: "object"
        fields:
          - {label: "Descrição curta", name: "twitterlike", widget: "text"}
          - {label: "Descrição longa", name: "2paraph", widget: "markdown"}
          
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
